export const LEAGUE_LABELS = {
  nba: {
    finals: "NBA Finals",
    round1: "First Round",
    semis: "Conf. Semis",
    confFinal: "Conf. Finals",
    playoffsSupported: true,
    playInSupported: true,
    bracketKeys: ["r1", "semis", "confFinals"],
    bracketTitles: { r1: "First Round", semis: "Conf. Semis", confFinals: "Conf. Finals" },
    finalsKey: "finals",
    round1SeriesCount: 4,
    conferences: [
      { key: "eastern", label: "Eastern" },
      { key: "western", label: "Western" },
    ],
  },
  nhl: {
    finals: "Stanley Cup Final",
    round1: "First Round",
    semis: "Second Round",
    confFinal: "Conf. Finals",
    playoffsSupported: true,
    playInSupported: false,
    bracketKeys: ["r1", "semis", "confFinals"],
    bracketTitles: { r1: "First Round", semis: "Second Round", confFinals: "Conf. Finals" },
    finalsKey: "finals",
    round1SeriesCount: 4,
    conferences: [
      { key: "eastern", label: "Eastern" },
      { key: "western", label: "Western" },
    ],
  },
  nfl: {
    finals: "Super Bowl",
    round1: "Wild Card",
    semis: "Divisional",
    confFinal: "Conf. Championship",
    playoffsSupported: true,
    playInSupported: false,
    bracketKeys: ["wildCard", "divisional", "confChampionship"],
    bracketTitles: { wildCard: "Wild Card", divisional: "Divisional", confChampionship: "Conf. Championship" },
    finalsKey: "superBowl",
    round1SeriesCount: 3,
    conferences: [
      { key: "afc", label: "AFC" },
      { key: "nfc", label: "NFC" },
    ],
  },
};
