name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '!backend/**/*.md'
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'
      - '!backend/**/*.md'
  workflow_dispatch:

jobs:
  Backend-CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: cd backend && npm ci

      - name: Verify
        run: cd backend && npm run verify
